<?php
/**
 * Class : web_menu
 * Date : 2014-05-15 23:06:02
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_menu {

	public $id_menu=null;
	public $title_al=null;
	public $title_en=null;
	public $link=null;
	public $class=null;
	public $menu_parent=null;
	public $menu_order=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_menu() {}
	public function get_by_id_menu($id) {
		$SQL = "select * from `web_menu` where `id_menu` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_menu = $row['id_menu'];
			$this->title_al = $row['title_al'];
			$this->title_en = $row['title_en'];
			$this->link = $row['link'];
			$this->class = $row['class'];
			$this->menu_parent = $row['menu_parent'];
			$this->menu_order = $row['menu_order'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_menu
	 */
	public function GetAll() {
		$SQL = "select * from `web_menu` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_menu();
			$item->id_menu = $row['id_menu'];
			$item->title_al = $row['title_al'];
			$item->title_en = $row['title_en'];
			$item->link = $row['link'];
			$item->class = $row['class'];
			$item->menu_parent = $row['menu_parent'];
			$item->menu_order = $row['menu_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_menu
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_menu` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_menu();
			$item->id_menu = $row['id_menu'];
			$item->title_al = $row['title_al'];
			$item->title_en = $row['title_en'];
			$item->link = $row['link'];
			$item->class = $row['class'];
			$item->menu_parent = $row['menu_parent'];
			$item->menu_order = $row['menu_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of menu_parent
	 *
	 */
	public function get_by_menu_parent($id) {
		$SQL = "select * from `web_menu` where menu_parent='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_menu();
			$item->id_menu = $row['id_menu'];
			$item->title_al = $row['title_al'];
			$item->title_en = $row['title_en'];
			$item->link = $row['link'];
			$item->class = $row['class'];
			$item->menu_parent = $row['menu_parent'];
			$item->menu_order = $row['menu_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_menu`(`title_al`,`title_en`,`link`,`class`,`menu_parent`,`menu_order`) values(
		'".mysql_real_escape_string($this->title_al)."'
,		'".mysql_real_escape_string($this->title_en)."'
,		'".mysql_real_escape_string($this->link)."'
,		'".mysql_real_escape_string($this->class)."'
,		'".mysql_real_escape_string($this->menu_parent)."'
,		'".mysql_real_escape_string($this->menu_order)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_menu=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_menu` set 
		`title_al`='".mysql_real_escape_string($this->title_al)."'
,		`title_en`='".mysql_real_escape_string($this->title_en)."'
,		`link`='".mysql_real_escape_string($this->link)."'
,		`class`='".mysql_real_escape_string($this->class)."'
,		`menu_parent`='".mysql_real_escape_string($this->menu_parent)."'
,		`menu_order`='".mysql_real_escape_string($this->menu_order)."'
		where `id_menu`='".mysql_real_escape_string($this->id_menu)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_menu` where `id_menu`='".mysql_real_escape_string($this->id_menu)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
