<?php
/**
 * Class : web_menu
 * Date : 2014-11-03 01:09:19
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_menu {

	public $id_menu=null;
	public $menu_title=null;
	public $menu_desc=null;
	public $menu_link=null;
	public $menu_class=null;
	public $id_parent=null;
	public $menu_order=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_menu() {}
	public function get_by_id_menu($id) {
		$SQL = "select * from `web_menu` where `id_menu` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_menu = $row['id_menu'];
			$this->menu_title = $row['menu_title'];
			$this->menu_desc = $row['menu_desc'];
			$this->menu_link = $row['menu_link'];
			$this->menu_class = $row['menu_class'];
			$this->id_parent = $row['id_parent'];
			$this->menu_order = $row['menu_order'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_menu
	 */
	public function GetAll() {
		$SQL = "select * from `web_menu` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_menu();
			$item->id_menu = $row['id_menu'];
			$item->menu_title = $row['menu_title'];
			$item->menu_desc = $row['menu_desc'];
			$item->menu_link = $row['menu_link'];
			$item->menu_class = $row['menu_class'];
			$item->id_parent = $row['id_parent'];
			$item->menu_order = $row['menu_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_menu
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_menu` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_menu();
			$item->id_menu = $row['id_menu'];
			$item->menu_title = $row['menu_title'];
			$item->menu_desc = $row['menu_desc'];
			$item->menu_link = $row['menu_link'];
			$item->menu_class = $row['menu_class'];
			$item->id_parent = $row['id_parent'];
			$item->menu_order = $row['menu_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of id_parent
	 *
	 */
	public function get_by_id_parent($id) {
		$SQL = "select * from `web_menu` where id_parent='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_menu();
			$item->id_menu = $row['id_menu'];
			$item->menu_title = $row['menu_title'];
			$item->menu_desc = $row['menu_desc'];
			$item->menu_link = $row['menu_link'];
			$item->menu_class = $row['menu_class'];
			$item->id_parent = $row['id_parent'];
			$item->menu_order = $row['menu_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_menu`(`menu_title`,`menu_desc`,`menu_link`,`menu_class`,`id_parent`,`menu_order`) values(
		'".mysql_real_escape_string($this->menu_title)."'
,		'".mysql_real_escape_string($this->menu_desc)."'
,		'".mysql_real_escape_string($this->menu_link)."'
,		'".mysql_real_escape_string($this->menu_class)."'
,		'".mysql_real_escape_string($this->id_parent)."'
,		'".mysql_real_escape_string($this->menu_order)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_menu=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_menu` set 
		`menu_title`='".mysql_real_escape_string($this->menu_title)."'
,		`menu_desc`='".mysql_real_escape_string($this->menu_desc)."'
,		`menu_link`='".mysql_real_escape_string($this->menu_link)."'
,		`menu_class`='".mysql_real_escape_string($this->menu_class)."'
,		`id_parent`='".mysql_real_escape_string($this->id_parent)."'
,		`menu_order`='".mysql_real_escape_string($this->menu_order)."'
		where `id_menu`='".mysql_real_escape_string($this->id_menu)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_menu` where `id_menu`='".mysql_real_escape_string($this->id_menu)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
