<?php
/**
 * Class : web_rolerights
 * Date : 2014-10-08 01:52:11
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_rolerights {

	public $id_rolerights=null;
	public $id_role=null;
	public $id_rights=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_rolerights() {}
	public function get_by_id_rolerights($id) {
		$SQL = "select * from `web_rolerights` where `id_rolerights` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_rolerights = $row['id_rolerights'];
			$this->id_role = $row['id_role'];
			$this->id_rights = $row['id_rights'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_rolerights
	 */
	public function GetAll() {
		$SQL = "select * from `web_rolerights` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_rolerights();
			$item->id_rolerights = $row['id_rolerights'];
			$item->id_role = $row['id_role'];
			$item->id_rights = $row['id_rights'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_rolerights
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_rolerights` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_rolerights();
			$item->id_rolerights = $row['id_rolerights'];
			$item->id_role = $row['id_role'];
			$item->id_rights = $row['id_rights'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Unique Methods

	/**
	 * Gets value of unique key
	 *
	 */
	public function get_by_unique($id_role,$id_rights,$a=null){
		$SQL = "select * from `web_rolerights` where 1 and `id_role`='".$id_role."' and `id_rights`='".$id_rights."' ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_rolerights = $row['id_rolerights'];
			$this->id_role = $row['id_role'];
			$this->id_rights = $row['id_rights'];
		}
		return $this;
	}

	// Indexer Methods

	/**
	 * Gets value of id_role
	 *
	 */
	public function get_by_id_role($id) {
		$SQL = "select * from `web_rolerights` where id_role='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_rolerights();
			$item->id_rolerights = $row['id_rolerights'];
			$item->id_role = $row['id_role'];
			$item->id_rights = $row['id_rights'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of id_rights
	 *
	 */
	public function get_by_id_rights($id) {
		$SQL = "select * from `web_rolerights` where id_rights='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_rolerights();
			$item->id_rolerights = $row['id_rolerights'];
			$item->id_role = $row['id_role'];
			$item->id_rights = $row['id_rights'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_rolerights`(`id_role`,`id_rights`) values(
		'".mysql_real_escape_string($this->id_role)."'
,		'".mysql_real_escape_string($this->id_rights)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_rolerights=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_rolerights` set 
		`id_role`='".mysql_real_escape_string($this->id_role)."'
,		`id_rights`='".mysql_real_escape_string($this->id_rights)."'
		where `id_rolerights`='".mysql_real_escape_string($this->id_rolerights)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_rolerights` where `id_rolerights`='".mysql_real_escape_string($this->id_rolerights)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
