<?php
/**
 * Class : web_options
 * Date : 2014-05-15 23:06:03
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_options {

	public $option_id=null;
	public $option_name=null;
	public $option_value=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_options() {}
	public function get_by_option_id($id) {
		$SQL = "select * from `web_options` where `option_id` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->option_id = $row['option_id'];
			$this->option_name = $row['option_name'];
			$this->option_value = $row['option_value'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_options
	 */
	public function GetAll() {
		$SQL = "select * from `web_options` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_options();
			$item->option_id = $row['option_id'];
			$item->option_name = $row['option_name'];
			$item->option_value = $row['option_value'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_options
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_options` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_options();
			$item->option_id = $row['option_id'];
			$item->option_name = $row['option_name'];
			$item->option_value = $row['option_value'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Unique Methods

	/**
	 * Gets value of unique key
	 *
	 */
	public function get_by_unique($option_name,$a=null){
		$SQL = "select * from `web_options` where 1 and `option_name`='".$option_name."' ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->option_id = $row['option_id'];
			$this->option_name = $row['option_name'];
			$this->option_value = $row['option_value'];
		}
		return $this;
	}

	public function Insert() {
		$SQL = "insert into `web_options`(`option_name`,`option_value`) values(
		'".mysql_real_escape_string($this->option_name)."'
,		'".mysql_real_escape_string($this->option_value)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->option_id=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_options` set 
		`option_name`='".mysql_real_escape_string($this->option_name)."'
,		`option_value`='".mysql_real_escape_string($this->option_value)."'
		where `option_id`='".mysql_real_escape_string($this->option_id)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_options` where `option_id`='".mysql_real_escape_string($this->option_id)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
