<?php
/**
 * Class : web_rights
 * Date : 2014-10-08 01:52:10
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_rights {

	public $id_rights=null;
	public $action=null;
	public $description=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_rights() {}
	public function get_by_id_rights($id) {
		$SQL = "select * from `web_rights` where `id_rights` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_rights = $row['id_rights'];
			$this->action = $row['action'];
			$this->description = $row['description'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_rights
	 */
	public function GetAll() {
		$SQL = "select * from `web_rights` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_rights();
			$item->id_rights = $row['id_rights'];
			$item->action = $row['action'];
			$item->description = $row['description'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_rights
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_rights` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_rights();
			$item->id_rights = $row['id_rights'];
			$item->action = $row['action'];
			$item->description = $row['description'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Unique Methods

	/**
	 * Gets value of unique key
	 *
	 */
	public function get_by_unique($action,$a=null){
		$SQL = "select * from `web_rights` where 1 and `action`='".$action."' ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_rights = $row['id_rights'];
			$this->action = $row['action'];
			$this->description = $row['description'];
		}
		return $this;
	}

	public function Insert() {
		$SQL = "insert into `web_rights`(`action`,`description`) values(
		'".mysql_real_escape_string($this->action)."'
,		'".mysql_real_escape_string($this->description)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_rights=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_rights` set 
		`action`='".mysql_real_escape_string($this->action)."'
,		`description`='".mysql_real_escape_string($this->description)."'
		where `id_rights`='".mysql_real_escape_string($this->id_rights)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_rights` where `id_rights`='".mysql_real_escape_string($this->id_rights)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
