<?php
/**
 * Class : web_users
 * Date : 2014-10-08 01:52:17
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_users {

	public $id_user=null;
	public $id_role=null;
	public $user_display_name=null;
	public $user_email=null;
	public $user_login=null;
	public $user_pass=null;
	public $user_mobile=null;
	public $user_registered=null;
	public $user_activation_key=null;
	public $openid=null;
	public $id_status=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_users() {}
	public function get_by_id_user($id) {
		$SQL = "select * from `web_users` where `id_user` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_user = $row['id_user'];
			$this->id_role = $row['id_role'];
			$this->user_display_name = $row['user_display_name'];
			$this->user_email = $row['user_email'];
			$this->user_login = $row['user_login'];
			$this->user_pass = $row['user_pass'];
			$this->user_mobile = $row['user_mobile'];
			$this->user_registered = $row['user_registered'];
			$this->user_activation_key = $row['user_activation_key'];
			$this->openid = $row['openid'];
			$this->id_status = $row['id_status'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_users
	 */
	public function GetAll() {
		$SQL = "select * from `web_users` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_users();
			$item->id_user = $row['id_user'];
			$item->id_role = $row['id_role'];
			$item->user_display_name = $row['user_display_name'];
			$item->user_email = $row['user_email'];
			$item->user_login = $row['user_login'];
			$item->user_pass = $row['user_pass'];
			$item->user_mobile = $row['user_mobile'];
			$item->user_registered = $row['user_registered'];
			$item->user_activation_key = $row['user_activation_key'];
			$item->openid = $row['openid'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_users
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_users` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_users();
			$item->id_user = $row['id_user'];
			$item->id_role = $row['id_role'];
			$item->user_display_name = $row['user_display_name'];
			$item->user_email = $row['user_email'];
			$item->user_login = $row['user_login'];
			$item->user_pass = $row['user_pass'];
			$item->user_mobile = $row['user_mobile'];
			$item->user_registered = $row['user_registered'];
			$item->user_activation_key = $row['user_activation_key'];
			$item->openid = $row['openid'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Unique Methods

	/**
	 * Gets value of unique key
	 *
	 */
	public function get_by_unique($user_email,$a=null){
		$SQL = "select * from `web_users` where 1 and `user_email`='".$user_email."' ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_user = $row['id_user'];
			$this->id_role = $row['id_role'];
			$this->user_display_name = $row['user_display_name'];
			$this->user_email = $row['user_email'];
			$this->user_login = $row['user_login'];
			$this->user_pass = $row['user_pass'];
			$this->user_mobile = $row['user_mobile'];
			$this->user_registered = $row['user_registered'];
			$this->user_activation_key = $row['user_activation_key'];
			$this->openid = $row['openid'];
			$this->id_status = $row['id_status'];
		}
		return $this;
	}

	// Indexer Methods

	/**
	 * Gets value of id_role
	 *
	 */
	public function get_by_id_role($id) {
		$SQL = "select * from `web_users` where id_role='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_users();
			$item->id_user = $row['id_user'];
			$item->id_role = $row['id_role'];
			$item->user_display_name = $row['user_display_name'];
			$item->user_email = $row['user_email'];
			$item->user_login = $row['user_login'];
			$item->user_pass = $row['user_pass'];
			$item->user_mobile = $row['user_mobile'];
			$item->user_registered = $row['user_registered'];
			$item->user_activation_key = $row['user_activation_key'];
			$item->openid = $row['openid'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_users`(`id_role`,`user_display_name`,`user_email`,`user_login`,`user_pass`,`user_mobile`,`user_registered`,`user_activation_key`,`openid`,`id_status`) values(
		'".mysql_real_escape_string($this->id_role)."'
,		'".mysql_real_escape_string($this->user_display_name)."'
,		'".mysql_real_escape_string($this->user_email)."'
,		'".mysql_real_escape_string($this->user_login)."'
,		'".mysql_real_escape_string($this->user_pass)."'
,		'".mysql_real_escape_string($this->user_mobile)."'
,		'".mysql_real_escape_string($this->user_registered)."'
,		'".mysql_real_escape_string($this->user_activation_key)."'
,		'".mysql_real_escape_string($this->openid)."'
,		'".mysql_real_escape_string($this->id_status)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_user=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_users` set 
		`id_role`='".mysql_real_escape_string($this->id_role)."'
,		`user_display_name`='".mysql_real_escape_string($this->user_display_name)."'
,		`user_email`='".mysql_real_escape_string($this->user_email)."'
,		`user_login`='".mysql_real_escape_string($this->user_login)."'
,		`user_pass`='".mysql_real_escape_string($this->user_pass)."'
,		`user_mobile`='".mysql_real_escape_string($this->user_mobile)."'
,		`user_registered`='".mysql_real_escape_string($this->user_registered)."'
,		`user_activation_key`='".mysql_real_escape_string($this->user_activation_key)."'
,		`openid`='".mysql_real_escape_string($this->openid)."'
,		`id_status`='".mysql_real_escape_string($this->id_status)."'
		where `id_user`='".mysql_real_escape_string($this->id_user)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_users` where `id_user`='".mysql_real_escape_string($this->id_user)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
