<?php
/**
 * Class : web_language
 * Date : 2014-10-08 01:52:08
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_language {

	public $lang_code=null;
	public $lang_desc=null;
	public $lang_flag=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_language() {}
	public function get_by_lang_code($id) {
		$SQL = "select * from `web_language` where `lang_code` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->lang_code = $row['lang_code'];
			$this->lang_desc = $row['lang_desc'];
			$this->lang_flag = $row['lang_flag'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_language
	 */
	public function GetAll() {
		$SQL = "select * from `web_language` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_language();
			$item->lang_code = $row['lang_code'];
			$item->lang_desc = $row['lang_desc'];
			$item->lang_flag = $row['lang_flag'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_language
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_language` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_language();
			$item->lang_code = $row['lang_code'];
			$item->lang_desc = $row['lang_desc'];
			$item->lang_flag = $row['lang_flag'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_language`(`lang_desc`,`lang_flag`) values(
		'".mysql_real_escape_string($this->lang_desc)."'
,		'".mysql_real_escape_string($this->lang_flag)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->lang_code=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_language` set 
		`lang_desc`='".mysql_real_escape_string($this->lang_desc)."'
,		`lang_flag`='".mysql_real_escape_string($this->lang_flag)."'
		where `lang_code`='".mysql_real_escape_string($this->lang_code)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_language` where `lang_code`='".mysql_real_escape_string($this->lang_code)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
