<?php
/**
 * Class : web_currency
 * Date : 2014-10-08 01:52:06
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_currency {

	public $ccy_code=null;
	public $ccy_desc=null;
	public $ccy_rate=null;
	public $ccy_flag=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_currency() {}
	public function get_by_ccy_code($id) {
		$SQL = "select * from `web_currency` where `ccy_code` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->ccy_code = $row['ccy_code'];
			$this->ccy_desc = $row['ccy_desc'];
			$this->ccy_rate = $row['ccy_rate'];
			$this->ccy_flag = $row['ccy_flag'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_currency
	 */
	public function GetAll() {
		$SQL = "select * from `web_currency` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_currency();
			$item->ccy_code = $row['ccy_code'];
			$item->ccy_desc = $row['ccy_desc'];
			$item->ccy_rate = $row['ccy_rate'];
			$item->ccy_flag = $row['ccy_flag'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_currency
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_currency` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_currency();
			$item->ccy_code = $row['ccy_code'];
			$item->ccy_desc = $row['ccy_desc'];
			$item->ccy_rate = $row['ccy_rate'];
			$item->ccy_flag = $row['ccy_flag'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_currency`(`ccy_desc`,`ccy_rate`,`ccy_flag`) values(
		'".mysql_real_escape_string($this->ccy_desc)."'
,		'".mysql_real_escape_string($this->ccy_rate)."'
,		'".mysql_real_escape_string($this->ccy_flag)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->ccy_code=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_currency` set 
		`ccy_desc`='".mysql_real_escape_string($this->ccy_desc)."'
,		`ccy_rate`='".mysql_real_escape_string($this->ccy_rate)."'
,		`ccy_flag`='".mysql_real_escape_string($this->ccy_flag)."'
		where `ccy_code`='".mysql_real_escape_string($this->ccy_code)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_currency` where `ccy_code`='".mysql_real_escape_string($this->ccy_code)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
