<?php
/**
 * Class : web_users
 * Date : 2014-05-15 23:06:08
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_users {

	public $id=null;
	public $user_login=null;
	public $user_pass=null;
	public $id_role=null;
	public $user_email=null;
	public $user_url=null;
	public $user_registered=null;
	public $user_activation_key=null;
	public $user_status=null;
	public $display_name=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_users() {}
	public function get_by_id($id) {
		$SQL = "select * from `web_users` where `ID` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id = $row['ID'];
			$this->user_login = $row['user_login'];
			$this->user_pass = $row['user_pass'];
			$this->id_role = $row['id_role'];
			$this->user_email = $row['user_email'];
			$this->user_url = $row['user_url'];
			$this->user_registered = $row['user_registered'];
			$this->user_activation_key = $row['user_activation_key'];
			$this->user_status = $row['user_status'];
			$this->display_name = $row['display_name'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_users
	 */
	public function GetAll() {
		$SQL = "select * from `web_users` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_users();
			$item->id = $row['ID'];
			$item->user_login = $row['user_login'];
			$item->user_pass = $row['user_pass'];
			$item->id_role = $row['id_role'];
			$item->user_email = $row['user_email'];
			$item->user_url = $row['user_url'];
			$item->user_registered = $row['user_registered'];
			$item->user_activation_key = $row['user_activation_key'];
			$item->user_status = $row['user_status'];
			$item->display_name = $row['display_name'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_users
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_users` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_users();
			$item->id = $row['ID'];
			$item->user_login = $row['user_login'];
			$item->user_pass = $row['user_pass'];
			$item->id_role = $row['id_role'];
			$item->user_email = $row['user_email'];
			$item->user_url = $row['user_url'];
			$item->user_registered = $row['user_registered'];
			$item->user_activation_key = $row['user_activation_key'];
			$item->user_status = $row['user_status'];
			$item->display_name = $row['display_name'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of user_login
	 *
	 */
	public function get_by_user_login($id) {
		$SQL = "select * from `web_users` where user_login='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_users();
			$item->id = $row['ID'];
			$item->user_login = $row['user_login'];
			$item->user_pass = $row['user_pass'];
			$item->id_role = $row['id_role'];
			$item->user_email = $row['user_email'];
			$item->user_url = $row['user_url'];
			$item->user_registered = $row['user_registered'];
			$item->user_activation_key = $row['user_activation_key'];
			$item->user_status = $row['user_status'];
			$item->display_name = $row['display_name'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_users`(`user_login`,`user_pass`,`id_role`,`user_email`,`user_url`,`user_registered`,`user_activation_key`,`user_status`,`display_name`) values(
		'".mysql_real_escape_string($this->user_login)."'
,		'".mysql_real_escape_string($this->user_pass)."'
,		'".mysql_real_escape_string($this->id_role)."'
,		'".mysql_real_escape_string($this->user_email)."'
,		'".mysql_real_escape_string($this->user_url)."'
,		'".mysql_real_escape_string($this->user_registered)."'
,		'".mysql_real_escape_string($this->user_activation_key)."'
,		'".mysql_real_escape_string($this->user_status)."'
,		'".mysql_real_escape_string($this->display_name)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_users` set 
		`user_login`='".mysql_real_escape_string($this->user_login)."'
,		`user_pass`='".mysql_real_escape_string($this->user_pass)."'
,		`id_role`='".mysql_real_escape_string($this->id_role)."'
,		`user_email`='".mysql_real_escape_string($this->user_email)."'
,		`user_url`='".mysql_real_escape_string($this->user_url)."'
,		`user_registered`='".mysql_real_escape_string($this->user_registered)."'
,		`user_activation_key`='".mysql_real_escape_string($this->user_activation_key)."'
,		`user_status`='".mysql_real_escape_string($this->user_status)."'
,		`display_name`='".mysql_real_escape_string($this->display_name)."'
		where `ID`='".mysql_real_escape_string($this->id)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_users` where `ID`='".mysql_real_escape_string($this->id)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
