<?php
/**
 * Class : web_roles
 * Date : 2014-05-15 23:06:06
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_roles {

	public $id_role=null;
	public $role=null;
	public $description=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_roles() {}
	public function get_by_id_role($id) {
		$SQL = "select * from `web_roles` where `id_role` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_role = $row['id_role'];
			$this->role = $row['role'];
			$this->description = $row['description'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_roles
	 */
	public function GetAll() {
		$SQL = "select * from `web_roles` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_roles();
			$item->id_role = $row['id_role'];
			$item->role = $row['role'];
			$item->description = $row['description'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_roles
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_roles` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_roles();
			$item->id_role = $row['id_role'];
			$item->role = $row['role'];
			$item->description = $row['description'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_roles`(`role`,`description`) values(
		'".mysql_real_escape_string($this->role)."'
,		'".mysql_real_escape_string($this->description)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_role=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_roles` set 
		`role`='".mysql_real_escape_string($this->role)."'
,		`description`='".mysql_real_escape_string($this->description)."'
		where `id_role`='".mysql_real_escape_string($this->id_role)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_roles` where `id_role`='".mysql_real_escape_string($this->id_role)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
