<?php
/**
 * Class : web_sms_logs
 * Date : 2014-10-08 01:52:15
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_sms_logs {

	public $id_sms=null;
	public $id_booking=null;
	public $mobile_nr=null;
	public $sms_text=null;
	public $sms_dt=null;
	public $delivery_result=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_sms_logs() {}
	public function get_by_id_sms($id) {
		$SQL = "select * from `web_sms_logs` where `id_sms` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_sms = $row['id_sms'];
			$this->id_booking = $row['id_booking'];
			$this->mobile_nr = $row['mobile_nr'];
			$this->sms_text = $row['sms_text'];
			$this->sms_dt = $row['sms_dt'];
			$this->delivery_result = $row['delivery_result'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_sms_logs
	 */
	public function GetAll() {
		$SQL = "select * from `web_sms_logs` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_sms_logs();
			$item->id_sms = $row['id_sms'];
			$item->id_booking = $row['id_booking'];
			$item->mobile_nr = $row['mobile_nr'];
			$item->sms_text = $row['sms_text'];
			$item->sms_dt = $row['sms_dt'];
			$item->delivery_result = $row['delivery_result'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_sms_logs
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_sms_logs` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_sms_logs();
			$item->id_sms = $row['id_sms'];
			$item->id_booking = $row['id_booking'];
			$item->mobile_nr = $row['mobile_nr'];
			$item->sms_text = $row['sms_text'];
			$item->sms_dt = $row['sms_dt'];
			$item->delivery_result = $row['delivery_result'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of id_booking
	 *
	 */
	public function get_by_id_booking($id) {
		$SQL = "select * from `web_sms_logs` where id_booking='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_sms_logs();
			$item->id_sms = $row['id_sms'];
			$item->id_booking = $row['id_booking'];
			$item->mobile_nr = $row['mobile_nr'];
			$item->sms_text = $row['sms_text'];
			$item->sms_dt = $row['sms_dt'];
			$item->delivery_result = $row['delivery_result'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_sms_logs`(`id_booking`,`mobile_nr`,`sms_text`,`sms_dt`,`delivery_result`) values(
		'".mysql_real_escape_string($this->id_booking)."'
,		'".mysql_real_escape_string($this->mobile_nr)."'
,		'".mysql_real_escape_string($this->sms_text)."'
,		'".mysql_real_escape_string($this->sms_dt)."'
,		'".mysql_real_escape_string($this->delivery_result)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_sms=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_sms_logs` set 
		`id_booking`='".mysql_real_escape_string($this->id_booking)."'
,		`mobile_nr`='".mysql_real_escape_string($this->mobile_nr)."'
,		`sms_text`='".mysql_real_escape_string($this->sms_text)."'
,		`sms_dt`='".mysql_real_escape_string($this->sms_dt)."'
,		`delivery_result`='".mysql_real_escape_string($this->delivery_result)."'
		where `id_sms`='".mysql_real_escape_string($this->id_sms)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_sms_logs` where `id_sms`='".mysql_real_escape_string($this->id_sms)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
