<?php
/**
 * Class : web_service
 * Date : 2014-10-16 08:17:43
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_service {

	public $id_service=null;
	public $id_parent=null;
	public $id_category=null;
	public $service_name=null;
	public $service_desc=null;
	public $service_price=null;
	public $service_nipt=null;
	public $service_email=null;
	public $service_mobile=null;
	public $service_address=null;
	public $service_rating=null;
	public $map_lat=null;
	public $map_lng=null;
	public $service_hours=null;
	public $service_img=null;
	public $dt_created=null;
	public $id_user=null;
	public $id_status=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_service() {}
	public function get_by_id_service($id) {
		$SQL = "select * from `web_service` where `id_service` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_service = $row['id_service'];
			$this->id_parent = $row['id_parent'];
			$this->id_category = $row['id_category'];
			$this->service_name = $row['service_name'];
			$this->service_desc = $row['service_desc'];
			$this->service_price = $row['service_price'];
			$this->service_nipt = $row['service_nipt'];
			$this->service_email = $row['service_email'];
			$this->service_mobile = $row['service_mobile'];
			$this->service_address = $row['service_address'];
			$this->service_rating = $row['service_rating'];
			$this->map_lat = $row['map_lat'];
			$this->map_lng = $row['map_lng'];
			$this->service_hours = $row['service_hours'];
			$this->service_img = $row['service_img'];
			$this->dt_created = $row['dt_created'];
			$this->id_user = $row['id_user'];
			$this->id_status = $row['id_status'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_service
	 */
	public function GetAll() {
		$SQL = "select * from `web_service` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_service();
			$item->id_service = $row['id_service'];
			$item->id_parent = $row['id_parent'];
			$item->id_category = $row['id_category'];
			$item->service_name = $row['service_name'];
			$item->service_desc = $row['service_desc'];
			$item->service_price = $row['service_price'];
			$item->service_nipt = $row['service_nipt'];
			$item->service_email = $row['service_email'];
			$item->service_mobile = $row['service_mobile'];
			$item->service_address = $row['service_address'];
			$item->service_rating = $row['service_rating'];
			$item->map_lat = $row['map_lat'];
			$item->map_lng = $row['map_lng'];
			$item->service_hours = $row['service_hours'];
			$item->service_img = $row['service_img'];
			$item->dt_created = $row['dt_created'];
			$item->id_user = $row['id_user'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_service
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_service` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_service();
			$item->id_service = $row['id_service'];
			$item->id_parent = $row['id_parent'];
			$item->id_category = $row['id_category'];
			$item->service_name = $row['service_name'];
			$item->service_desc = $row['service_desc'];
			$item->service_price = $row['service_price'];
			$item->service_nipt = $row['service_nipt'];
			$item->service_email = $row['service_email'];
			$item->service_mobile = $row['service_mobile'];
			$item->service_address = $row['service_address'];
			$item->service_rating = $row['service_rating'];
			$item->map_lat = $row['map_lat'];
			$item->map_lng = $row['map_lng'];
			$item->service_hours = $row['service_hours'];
			$item->service_img = $row['service_img'];
			$item->dt_created = $row['dt_created'];
			$item->id_user = $row['id_user'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of id_category
	 *
	 */
	public function get_by_id_category($id) {
		$SQL = "select * from `web_service` where id_category='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_service();
			$item->id_service = $row['id_service'];
			$item->id_parent = $row['id_parent'];
			$item->id_category = $row['id_category'];
			$item->service_name = $row['service_name'];
			$item->service_desc = $row['service_desc'];
			$item->service_price = $row['service_price'];
			$item->service_nipt = $row['service_nipt'];
			$item->service_email = $row['service_email'];
			$item->service_mobile = $row['service_mobile'];
			$item->service_address = $row['service_address'];
			$item->service_rating = $row['service_rating'];
			$item->map_lat = $row['map_lat'];
			$item->map_lng = $row['map_lng'];
			$item->service_hours = $row['service_hours'];
			$item->service_img = $row['service_img'];
			$item->dt_created = $row['dt_created'];
			$item->id_user = $row['id_user'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of id_parent
	 *
	 */
	public function get_by_id_parent($id) {
		$SQL = "select * from `web_service` where id_parent='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_service();
			$item->id_service = $row['id_service'];
			$item->id_parent = $row['id_parent'];
			$item->id_category = $row['id_category'];
			$item->service_name = $row['service_name'];
			$item->service_desc = $row['service_desc'];
			$item->service_price = $row['service_price'];
			$item->service_nipt = $row['service_nipt'];
			$item->service_email = $row['service_email'];
			$item->service_mobile = $row['service_mobile'];
			$item->service_address = $row['service_address'];
			$item->service_rating = $row['service_rating'];
			$item->map_lat = $row['map_lat'];
			$item->map_lng = $row['map_lng'];
			$item->service_hours = $row['service_hours'];
			$item->service_img = $row['service_img'];
			$item->dt_created = $row['dt_created'];
			$item->id_user = $row['id_user'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_service`(`id_parent`,`id_category`,`service_name`,`service_desc`,`service_price`,`service_nipt`,`service_email`,`service_mobile`,`service_address`,`service_rating`,`map_lat`,`map_lng`,`service_hours`,`service_img`,`dt_created`,`id_user`,`id_status`) values(
		'".mysql_real_escape_string($this->id_parent)."'
,		'".mysql_real_escape_string($this->id_category)."'
,		'".mysql_real_escape_string($this->service_name)."'
,		'".mysql_real_escape_string($this->service_desc)."'
,		'".mysql_real_escape_string($this->service_price)."'
,		'".mysql_real_escape_string($this->service_nipt)."'
,		'".mysql_real_escape_string($this->service_email)."'
,		'".mysql_real_escape_string($this->service_mobile)."'
,		'".mysql_real_escape_string($this->service_address)."'
,		'".mysql_real_escape_string($this->service_rating)."'
,		'".mysql_real_escape_string($this->map_lat)."'
,		'".mysql_real_escape_string($this->map_lng)."'
,		'".mysql_real_escape_string($this->service_hours)."'
,		'".mysql_real_escape_string($this->service_img)."'
,		'".mysql_real_escape_string($this->dt_created)."'
,		'".mysql_real_escape_string($this->id_user)."'
,		'".mysql_real_escape_string($this->id_status)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_service=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_service` set 
		`id_parent`='".mysql_real_escape_string($this->id_parent)."'
,		`id_category`='".mysql_real_escape_string($this->id_category)."'
,		`service_name`='".mysql_real_escape_string($this->service_name)."'
,		`service_desc`='".mysql_real_escape_string($this->service_desc)."'
,		`service_price`='".mysql_real_escape_string($this->service_price)."'
,		`service_nipt`='".mysql_real_escape_string($this->service_nipt)."'
,		`service_email`='".mysql_real_escape_string($this->service_email)."'
,		`service_mobile`='".mysql_real_escape_string($this->service_mobile)."'
,		`service_address`='".mysql_real_escape_string($this->service_address)."'
,		`service_rating`='".mysql_real_escape_string($this->service_rating)."'
,		`map_lat`='".mysql_real_escape_string($this->map_lat)."'
,		`map_lng`='".mysql_real_escape_string($this->map_lng)."'
,		`service_hours`='".mysql_real_escape_string($this->service_hours)."'
,		`service_img`='".mysql_real_escape_string($this->service_img)."'
,		`dt_created`='".mysql_real_escape_string($this->dt_created)."'
,		`id_user`='".mysql_real_escape_string($this->id_user)."'
,		`id_status`='".mysql_real_escape_string($this->id_status)."'
		where `id_service`='".mysql_real_escape_string($this->id_service)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_service` where `id_service`='".mysql_real_escape_string($this->id_service)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
