<?php
/**
 * Class : web_field_group
 * Date : 2014-10-16 08:17:41
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_field_group {

	public $id_group=null;
	public $group_name=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_field_group() {}
	public function get_by_id_group($id) {
		$SQL = "select * from `web_field_group` where `id_group` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_group = $row['id_group'];
			$this->group_name = $row['group_name'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_field_group
	 */
	public function GetAll() {
		$SQL = "select * from `web_field_group` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_field_group();
			$item->id_group = $row['id_group'];
			$item->group_name = $row['group_name'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_field_group
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_field_group` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_field_group();
			$item->id_group = $row['id_group'];
			$item->group_name = $row['group_name'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_field_group`(`group_name`) values(
		'".mysql_real_escape_string($this->group_name)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_group=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_field_group` set 
		`group_name`='".mysql_real_escape_string($this->group_name)."'
		where `id_group`='".mysql_real_escape_string($this->id_group)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_field_group` where `id_group`='".mysql_real_escape_string($this->id_group)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
