<?php
/**
 * Class : web_service_gallery
 * Date : 2014-10-08 01:52:14
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_service_gallery {

	public $id_gallery=null;
	public $id_service=null;
	public $img_desc=null;
	public $img_path=null;
	public $img_order=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_service_gallery() {}
	public function get_by_id_gallery($id) {
		$SQL = "select * from `web_service_gallery` where `id_gallery` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_gallery = $row['id_gallery'];
			$this->id_service = $row['id_service'];
			$this->img_desc = $row['img_desc'];
			$this->img_path = $row['img_path'];
			$this->img_order = $row['img_order'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_service_gallery
	 */
	public function GetAll() {
		$SQL = "select * from `web_service_gallery` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_service_gallery();
			$item->id_gallery = $row['id_gallery'];
			$item->id_service = $row['id_service'];
			$item->img_desc = $row['img_desc'];
			$item->img_path = $row['img_path'];
			$item->img_order = $row['img_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_service_gallery
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_service_gallery` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_service_gallery();
			$item->id_gallery = $row['id_gallery'];
			$item->id_service = $row['id_service'];
			$item->img_desc = $row['img_desc'];
			$item->img_path = $row['img_path'];
			$item->img_order = $row['img_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of id_service
	 *
	 */
	public function get_by_id_service($id) {
		$SQL = "select * from `web_service_gallery` where id_service='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_service_gallery();
			$item->id_gallery = $row['id_gallery'];
			$item->id_service = $row['id_service'];
			$item->img_desc = $row['img_desc'];
			$item->img_path = $row['img_path'];
			$item->img_order = $row['img_order'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_service_gallery`(`id_service`,`img_desc`,`img_path`,`img_order`) values(
		'".mysql_real_escape_string($this->id_service)."'
,		'".mysql_real_escape_string($this->img_desc)."'
,		'".mysql_real_escape_string($this->img_path)."'
,		'".mysql_real_escape_string($this->img_order)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_gallery=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_service_gallery` set 
		`id_service`='".mysql_real_escape_string($this->id_service)."'
,		`img_desc`='".mysql_real_escape_string($this->img_desc)."'
,		`img_path`='".mysql_real_escape_string($this->img_path)."'
,		`img_order`='".mysql_real_escape_string($this->img_order)."'
		where `id_gallery`='".mysql_real_escape_string($this->id_gallery)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_service_gallery` where `id_gallery`='".mysql_real_escape_string($this->id_gallery)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
