<?php
/**
 * Class : web_booking
 * Date : 2014-10-08 01:52:04
 * 
 * This class was auto-generated by Database ORM
 * (Besmir Alia, besmiralia@gmail.com)
 */
include_once('start.php');
include_once('config.php');
include_once('db.php');

class web_booking {

	public $id_booking=null;
	public $id_service=null;
	public $id_user=null;
	public $dt_booking=null;
	public $dt_start=null;
	public $dt_end=null;
	public $booking_notes=null;
	public $rating=null;
	public $review=null;
	public $id_status=null;

	/**
	 * Public Constructor
	 *
	 */
	public function web_booking() {}
	public function get_by_id_booking($id) {
		$SQL = "select * from `web_booking` where `id_booking` = '".mysql_real_escape_string($id)."' limit 1";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		if ($row = mysql_fetch_array($result)) {
			$this->id_booking = $row['id_booking'];
			$this->id_service = $row['id_service'];
			$this->id_user = $row['id_user'];
			$this->dt_booking = $row['dt_booking'];
			$this->dt_start = $row['dt_start'];
			$this->dt_end = $row['dt_end'];
			$this->booking_notes = $row['booking_notes'];
			$this->rating = $row['rating'];
			$this->review = $row['review'];
			$this->id_status = $row['id_status'];
		}
		return $this;
	}

	/**
	 * GetAll
	 *
	 * @return Array() of web_booking
	 */
	public function GetAll() {
		$SQL = "select * from `web_booking` ";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_booking();
			$item->id_booking = $row['id_booking'];
			$item->id_service = $row['id_service'];
			$item->id_user = $row['id_user'];
			$item->dt_booking = $row['dt_booking'];
			$item->dt_start = $row['dt_start'];
			$item->dt_end = $row['dt_end'];
			$item->booking_notes = $row['booking_notes'];
			$item->rating = $row['rating'];
			$item->review = $row['review'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	/**
	 * Find
	 *
	 * @return Array() of web_booking
	 */
	public function Find($findStr) {
		$SQL = "select * from `web_booking` where ".$findStr;
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_booking();
			$item->id_booking = $row['id_booking'];
			$item->id_service = $row['id_service'];
			$item->id_user = $row['id_user'];
			$item->dt_booking = $row['dt_booking'];
			$item->dt_start = $row['dt_start'];
			$item->dt_end = $row['dt_end'];
			$item->booking_notes = $row['booking_notes'];
			$item->rating = $row['rating'];
			$item->review = $row['review'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	// Indexer Methods

	/**
	 * Gets value of id_service
	 *
	 */
	public function get_by_id_service($id) {
		$SQL = "select * from `web_booking` where id_service='".$id."'";
		$result = mysql_query($SQL) or die("Error in SQL Syntax: $SQL," . mysql_error());

		$items = array();$i=0;
		while ($row = mysql_fetch_array($result)) {
			$item = new web_booking();
			$item->id_booking = $row['id_booking'];
			$item->id_service = $row['id_service'];
			$item->id_user = $row['id_user'];
			$item->dt_booking = $row['dt_booking'];
			$item->dt_start = $row['dt_start'];
			$item->dt_end = $row['dt_end'];
			$item->booking_notes = $row['booking_notes'];
			$item->rating = $row['rating'];
			$item->review = $row['review'];
			$item->id_status = $row['id_status'];
			$items[$i++]=$item;
		}
		return $items;
	}

	public function Insert() {
		$SQL = "insert into `web_booking`(`id_service`,`id_user`,`dt_booking`,`dt_start`,`dt_end`,`booking_notes`,`rating`,`review`,`id_status`) values(
		'".mysql_real_escape_string($this->id_service)."'
,		'".mysql_real_escape_string($this->id_user)."'
,		'".mysql_real_escape_string($this->dt_booking)."'
,		'".mysql_real_escape_string($this->dt_start)."'
,		'".mysql_real_escape_string($this->dt_end)."'
,		'".mysql_real_escape_string($this->booking_notes)."'
,		'".mysql_real_escape_string($this->rating)."'
,		'".mysql_real_escape_string($this->review)."'
,		'".mysql_real_escape_string($this->id_status)."')";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else{$this->id_booking=mysql_insert_id();
			return $this;}
	}

	public function Update() {
		$SQL = "update `web_booking` set 
		`id_service`='".mysql_real_escape_string($this->id_service)."'
,		`id_user`='".mysql_real_escape_string($this->id_user)."'
,		`dt_booking`='".mysql_real_escape_string($this->dt_booking)."'
,		`dt_start`='".mysql_real_escape_string($this->dt_start)."'
,		`dt_end`='".mysql_real_escape_string($this->dt_end)."'
,		`booking_notes`='".mysql_real_escape_string($this->booking_notes)."'
,		`rating`='".mysql_real_escape_string($this->rating)."'
,		`review`='".mysql_real_escape_string($this->review)."'
,		`id_status`='".mysql_real_escape_string($this->id_status)."'
		where `id_booking`='".mysql_real_escape_string($this->id_booking)."' limit 1";
		$result = mysql_query($SQL);
		if ($result === false)
			return null;
		else
			return $this;
	}

	public function Delete() {
		$SQL = "Delete from `web_booking` where `id_booking`='".mysql_real_escape_string($this->id_booking)."' limit 1";
		$result = mysql_query($SQL);
		 return $result;
	}

}
